# Generated by Django 5.0.2 on 2024-02-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_softskillstory_options'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default="2020-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='demo',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='pet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(related_name='projects', to='core.hardskill'),
        ),
    ]
