# Generated by Django 5.0.2 on 2024-02-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_created_at_project_demo_project_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
