# Generated by Django 5.0.2 on 2024-02-15 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.SmallIntegerField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('birth_date', models.DateField()),
                ('location', models.CharField(max_length=70)),
                ('greating_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.ImageField(upload_to='icons/')),
                ('description', models.TextField()),
                ('reading', models.CharField(choices=[('b', 'Beginner'), ('i', 'Intermediate'), ('a', 'Advanced')], max_length=1)),
                ('speaking', models.CharField(choices=[('b', 'Beginner'), ('i', 'Intermediate'), ('a', 'Advanced')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.ImageField(upload_to='icons/')),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('b', 'Beginner'), ('i', 'Intermediate'), ('a', 'Advanced')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skillcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
