# Generated by Django 5.0.2 on 2024-02-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bio',
            options={'verbose_name_plural': 'Bio'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'Skill Categories'},
        ),
    ]
