# Generated by Django 5.0.2 on 2024-02-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bio_options_alter_skillcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
