# Generated by Django 5.0.2 on 2024-02-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bio_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.ImageField(upload_to='icons/')),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('b', 'Beginner'), ('i', 'Intermediate'), ('a', 'Advanced')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoftSkillStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team/')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.ImageField(upload_to='icons/')),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('b', 'Beginner'), ('i', 'Intermediate'), ('a', 'Advanced')])),
                ('stories', models.ManyToManyField(related_name='soft_skills', to='core.softskillstory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
