# Generated by Django 5.0.2 on 2024-02-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hardskill_softskillstory_softskill_delete_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
