# Generated by Django 5.0.2 on 2024-02-18 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_skillcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softskill',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='softskill',
            name='level',
        ),
    ]
