# Generated by Django 5.0.2 on 2024-02-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_softskill_icon_remove_softskill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softskill',
            name='stories',
            field=models.ManyToManyField(blank=True, related_name='soft_skills', to='core.softskillstory'),
        ),
    ]
