# Generated by Django 5.0.2 on 2024-02-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_softskill_stories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softskillstory',
            options={'verbose_name_plural': 'Soft skills stories'},
        ),
    ]
