# Generated by Django 5.0.2 on 2024-02-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='message',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
